/**
 * ChatRequest，描述：对话请求对象
 */
export interface SendDTO {
  query?: string;
  agent_id?: number;
  sessionId?: string;
  user_id?: number;
  merchant_id?: number;
}

/**
 * Message，描述：
 */
export interface Message {
  content?: string;
  name?: string;
  reasoning_content?: string;
  /**
   * 目前支持四个中角色参考官网，进行情景输入：
   * https://platform.openai.com/docs/guides/chat/introduction
   */
  role?: 'system' | 'user' | 'assistant' | 'function' | 'tool';
  tool_call_id?: string;
  /**
   * The tool calls generated by the model, such as function calls.
   */
  tool_calls?: ToolCalls[];
}

/**
 * ToolCalls，The tool calls generated by the model, such as function calls.
 */
export interface ToolCalls {
  function?: ToolCallFunction;
  /**
   * The ID of the tool call.
   */
  id?: string;
  /**
   * The type of the tool. Currently, only function is supported.
   */
  type?: string;
}

/**
 * ToolCallFunction，ToolCall 的 Function参数
 * The function that the model called.
 */
export interface ToolCallFunction {
  /**
   * 方法参数
   */
  arguments?: string;
  /**
   * 方法名
   */
  name?: string;
}

export interface GetChatListParams {
  /**
   * 消息内容
   */
  content?: string;
  /**
   * 创建者
   */
  createBy?: number;
  /**
   * 创建部门
   */
  createDept?: number;
  /**
   * 创建时间
   */
  createTime?: Date;
  /**
   * 扣除金额
   */
  deductCost?: number;
  /**
   * 主键
   */
  id?: number;
  /**
   * 排序的方向desc或者asc
   */
  isAsc?: string;
  /**
   * 模型名称
   */
  modelName?: string;
  /**
   * 排序列
   */
  orderByColumn?: string;
  /**
   * 当前页数
   */
  pageNum?: number;
  /**
   * 分页大小
   */
  pageSize?: number;
  /**
   * 请求参数
   */
  params?: { [key: string]: { [key: string]: any } };
  /**
   * 备注
   */
  remark?: string;
  /**
   * 对话角色
   */
  role?: string;
  /**
   * 会话id (字符串格式)
   */
  sessionId?: string;
  /**
   * 累计 Tokens
   */
  totalTokens?: number;
  /**
   * 更新者
   */
  updateBy?: number;
  /**
   * 更新时间
   */
  updateTime?: Date;
  /**
   * 用户id
   */
  userId?: number;
}

/**
 * ChatMessageVo，聊天消息视图对象 chat_message
 */
export interface ChatMessageVo {
  /**
   * 消息内容
   */
  content?: string;
  /**
   * 扣除金额
   */
  deductCost?: number;
  /**
   * 主键
   */
  id?: number;
  /**
   * 模型名称
   */
  modelName?: string;
  /**
   * 备注
   */
  remark?: string;
  /**
   * 对话角色
   */
  role?: string;
  /**
   * 会话id (字符串格式)
   */
  sessionId?: string;
  /**
   * 会话ID（字符串格式，与sessionId保持一致）
   */
  conversation_id?: string;
  /**
   * 累计 Tokens
   */
  totalTokens?: number;
  /**
   * 估算的累计 Tokens
   */
  total_tokens_estimated?: number;
  /**
   * 消息费用
   */
  cost?: number;
  /**
   * 用户id
   */
  userId?: number;
  /**
   * 工作流事件
   */
  workflow_events?: any[];
  /**
   * 创建时间
   */
  created_at?: string;
  /**
   * 更新时间
   */
  updated_at?: string;
  /**
   * 消息关联的文件
   */
  files?: any[];
  /**
   * AI思考过程内容
   */
  thought_content?: string;
}
