version: '3.8'

services:
  web:
    build: 
      context: ../
      dockerfile: docker/Dockerfile
    container_name: wenke-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://wenke_user:wenke_password@db:5432/wenke_db
      - SECRET_KEY=${SECRET_KEY:-your-secret-key}
      - ALGORITHM=${ALGORITHM:-HS256}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      - DEBUG=${DEBUG:-False}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DIFY_API_BASE_URL=${DIFY_API_BASE_URL:-http://localhost:5001/v1}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - wenke-network
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  db:
    image: postgres:15-alpine
    container_name: wenke-db
    environment:
      - POSTGRES_USER=wenke_user
      - POSTGRES_PASSWORD=wenke_password
      - POSTGRES_DB=wenke_db
    ports:
      - "5432:5432"
    networks:
      - wenke-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  wenke-network:
    driver: bridge

volumes:
  postgres_data: